scripts: remove sudo when delete libte-iut.so
Not all users may be permitted to launch commands via sudo
without additional password verification. Lack of the permission
may be a cause of appearance of unwanted messages about necessity
to read the password by terminal. In l5_run script, we have removed
sudo from the command deleting libte-iut.so library on iut host to
prevent appearing of such redundant messages for users without
the privilege.

OL-Redmine-Id: 12650
Signed-off-by: Pavel Liulchak <pavel.liulchak@oktetlabs.ru>
Reviewed-by: Alexandra Kossovsky <alexandra.kossovsky@oktetlabs.ru>

diff --git a/scripts/l5_run b/scripts/l5_run
--- a/scripts/l5_run
+++ b/scripts/l5_run
@@ -61,7 +61,11 @@ else
     fi
 fi
 if test "x${SFC_ONLOAD_LOCAL}" != "xyes" ; then
-    ssh ${te_iut_host} "sudo rm /tmp/libte-iut.so"
+    ssh ${te_iut_host} "rm /tmp/libte-iut.so"
+
+    if [[ $? != 0 ]] ; then
+        fail "Unable to delete $LIB_PATH on ${te_iut_host} via ssh"
+    fi
 fi
 
 if test "$EF_IUT_EF10" = "true" ; then
